# Generated by Django 4.1.1 on 2022-09-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otzyv', to='movie_app.review', verbose_name='Отзыв'),
        ),
    ]
