# Generated by Django 4.1.1 on 2022-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_remove_movie_reviews_movie_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='film',
            field=models.ManyToManyField(related_name='cinema', to='movie_app.movie'),
        ),
    ]
