# Generated by Django 4.1.1 on 2022-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_raiting_movie_rai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='raiting',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
    ]
