# Generated by Django 4.1.1 on 2022-09-24 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_raiting_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rai',
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Raiting',
        ),
    ]
