# Generated by Django 4.1.1 on 2022-09-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_rename_rev_movie_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='director_name',
        ),
    ]
